stages:
  - rtl_chk
  - bhv_sim
  - run_syn
  - bit_gen
  - fpga_eval
  - repo_push

variables:
    GIT_SUBMODULE_STRATEGY: recursive

default:
  image: gitlab.agileserve.org.cn:15050/zelin/vivado-ci-tools/vivado-vnc-ci-multistage:v2.5
  tags: 
    - k8s
  before_script:
    - cd flow 

repo_push:
  stage: repo_push
  script:
    - echo "Commits have been pushed to master branch."
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"

rtl_chk:
  stage: rtl_chk
  script:
    - make HW_ACT=rtl_chk CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/run_log

memcpy_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=basic:01 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

sum_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:01 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

mov-c_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:02 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

fib_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:03 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

add_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:04 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

if-else_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:05 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

pascal_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:06 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

quick-sort_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:07 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

select-sort_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:08 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

max_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:09 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

min3_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:10 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

switch_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:11 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

bubble-sort_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=medium:12 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

shuixianhua_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:01 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

sub-longlong_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:02 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

bit_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:03 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

recursion_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:04 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

fact_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:05 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

add-longlong_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:06 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

shift_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:07 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

wanshu_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:08 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

goldbach_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:09 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

leap-year_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:10 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

prime_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:11 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

mul-longlong_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:12 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

load-store_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:13 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

to-lower-case_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:14 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

movsx_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:15 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

matrix-mul_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:16 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

unalign_bhv_sim:
  stage: bhv_sim
  script:
    - make HW_ACT=bhv_sim HW_VAL=advanced:17 CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/sim
      - flow/hardware/vivado_out/run_log

run_syn:
  stage: run_syn
  script:
    - make HW_ACT=run_syn CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/synth_rpt
      - flow/hardware/vivado_out/run_log

bit_gen:
  stage: bit_gen
  script:
    - make HW_ACT=bit_gen CI_RUN=y vivado_prj
  only:
    variables:
      - $CI_COMMIT_BRANCH == "run"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/hardware/vivado_out/impl_rpt
      - flow/hw_plat/
      - flow/hardware/vivado_out/run_log

fpga_eval:
  stage: fpga_eval
  tags:
    - nf
  script:
    - mkdir -p ./run/log 
    - cd run/
    - bash ci_run.sh | tee ./log/cloud_run.log
  only:
    variables:
      - $CI_COMMIT_BRANCH == "run"
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    paths:
      - flow/run/log/

